# An example YAML file

data:
  baseline: 'baseline_data'
    file1: 'baseline_data'
      file1_path: 'data/configuration_data/baseline_data.csv'



  module4: 'calc_ww_water_demand.py'
    file1: 'water_flow_targets'
      file1_path: 'data/configuration_data/cwwd_water_flow_targets.csv'


  module5: 'calc_water_sector_water_demand.py'
    file1: 'water_flow_targets'
      file1_path: 'data/configuration_data/cwswd_water_flow_targets.csv'


  module6: 'calc_water_sector_energy.py'
    file1: 'water_flow_targets'
      file1_path: 'data/configuration_data/cwse_water_flow_targets.csv'

    file2: 'water_sector_energy_split_fractions'
      file2_path: 'data/configuration_data/cwse_water_sector_energy_split_fractions.csv'

